version: "3"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  backend:
    build: backend
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_HOST: backend.localtest.me
      GO_ENV: development
      DB_DATABASE: postgres
      DB_HOST: db
      DB_PORT: 5432

  docs:
    image:  squidfunk/mkdocs-material
    volumes:
      - ./docs:/docs
    environment:
      VIRTUAL_HOST: docs.localtest.me

  db:
    image: postgres:10.10
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  phppgadmin:
    restart: always
    image: dockage/phppgadmin:latest
    ports:
    - "8888:80"
    environment:
      VIRTUAL_HOST: pgadmin.localtest.me
      PHP_PG_ADMIN_SERVER_DESC: PostgreSQL
      PHP_PG_ADMIN_SERVER_HOST: db
      PHP_PG_ADMIN_SERVER_PORT: 5432
      PHP_PG_ADMIN_SERVER_SSL_MODE: allow
      PHP_PG_ADMIN_SERVER_DEFAULT_DB:  ""