---
development:
  dialect: postgres
  database: {{envOr "DB_DATABASE" "backend_development" }}
  user: {{ envOr "DB_USER" "postgres"  }}
  host: {{envOr "DB_HOST" "127.0.0.1"  }}
  port: {{ envOr "DB_PORT" "5432"  }}
  password: {{ envOr "DB_PASSWORD" "postgres"  }}
  pool: 5

test:
  dialect: postgres
  database: {{envOr "DB_DATABASE" "backend_test" }}
  user: {{ envOr "DB_USER" "postgres"  }}
  host: {{envOr "DB_HOST" "127.0.0.1"  }}
  port: {{ envOr "DB_PORT" "5432"  }}
  password: {{ envOr "DB_PASSWORD" "postgres"  }}
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/backend_production?sslmode=disable"}}
