package actions

import (
	"backend/models"
	"fmt"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/gobuffalo/x/responder"
	"net/http"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Route)
// DB Table: Plural (routes)
// Resource: Plural (Routes)
// Path: Plural (/routes)
// View Template Folder: Plural (/templates/routes/)

// RoutesResource is the resource for the Route model
type RoutesResource struct {
	buffalo.Resource
}

// List gets all Routes. This function is mapped to the path
// GET /routes
func (v RoutesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	routes := &models.Routes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Routes from the DB
	if err := q.Eager().All(routes); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("routes", routes)
		return c.Render(http.StatusOK, r.HTML("/routes/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(routes))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(routes))
	}).Respond(c)
}

// Show gets the data for one Route. This function is mapped to
// the path GET /routes/{route_id}
func (v RoutesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Route
	route := &models.Route{}

	// To find the Route the parameter route_id is used.
	if err := tx.Find(route, c.Param("route_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("route", route)

		return c.Render(http.StatusOK, r.HTML("/routes/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(route))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(route))
	}).Respond(c)
}

// Create adds a Route to the DB. This function is mapped to the
// path POST /routes
func (v RoutesResource) Create(c buffalo.Context) error {
	// Allocate an empty Route
	route := &models.Route{}

	// Bind route to the html form elements
	if err := c.Bind(route); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(route)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("route", route)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/routes/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "route.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/routes/%v", route.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(route))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(route))
	}).Respond(c)
}

// Update changes a Route in the DB. This function is mapped to
// the path PUT /routes/{route_id}
func (v RoutesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Route
	route := &models.Route{}

	if err := tx.Find(route, c.Param("route_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Route to the html form elements
	if err := c.Bind(route); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(route)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("route", route)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/routes/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "route.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/routes/%v", route.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(route))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(route))
	}).Respond(c)
}

// Destroy deletes a Route from the DB. This function is mapped
// to the path DELETE /routes/{route_id}
func (v RoutesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Route
	route := &models.Route{}

	// To find the Route the parameter route_id is used.
	if err := tx.Find(route, c.Param("route_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(route); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "route.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/routes")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(route))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(route))
	}).Respond(c)
}
