package actions

import (
	"backend/models"
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Waypoint)
// DB Table: Plural (waypoints)
// Resource: Plural (Waypoints)
// Path: Plural (/waypoints)
// View Template Folder: Plural (/templates/waypoints/)

// WaypointsResource is the resource for the Waypoint model
type WaypointsResource struct {
	buffalo.Resource
}

// List gets all Waypoints. This function is mapped to the path
// GET /waypoints
func (v WaypointsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	waypoints := &models.Waypoints{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Waypoints from the DB
	if err := q.All(waypoints); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("waypoints", waypoints)
		return c.Render(http.StatusOK, r.HTML("/waypoints/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(waypoints))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(waypoints))
	}).Respond(c)
}

// Show gets the data for one Waypoint. This function is mapped to
// the path GET /waypoints/{waypoint_id}
func (v WaypointsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Waypoint
	waypoint := &models.Waypoint{}

	// To find the Waypoint the parameter waypoint_id is used.
	if err := tx.Find(waypoint, c.Param("waypoint_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("waypoint", waypoint)

		return c.Render(http.StatusOK, r.HTML("/waypoints/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(waypoint))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(waypoint))
	}).Respond(c)
}

// Create adds a Waypoint to the DB. This function is mapped to the
// path POST /waypoints
func (v WaypointsResource) Create(c buffalo.Context) error {
	// Allocate an empty Waypoint
	waypoint := &models.Waypoint{}

	// Bind waypoint to the html form elements
	if err := c.Bind(waypoint); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(waypoint)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("waypoint", waypoint)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/waypoints/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/waypoints/%v", waypoint.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(waypoint))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(waypoint))
	}).Respond(c)
}

// Update changes a Waypoint in the DB. This function is mapped to
// the path PUT /waypoints/{waypoint_id}
func (v WaypointsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Waypoint
	waypoint := &models.Waypoint{}

	if err := tx.Find(waypoint, c.Param("waypoint_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Waypoint to the html form elements
	if err := c.Bind(waypoint); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(waypoint)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("waypoint", waypoint)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/waypoints/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/waypoints/%v", waypoint.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(waypoint))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(waypoint))
	}).Respond(c)
}

// Destroy deletes a Waypoint from the DB. This function is mapped
// to the path DELETE /waypoints/{waypoint_id}
func (v WaypointsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Waypoint
	waypoint := &models.Waypoint{}

	// To find the Waypoint the parameter waypoint_id is used.
	if err := tx.Find(waypoint, c.Param("waypoint_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(waypoint); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/waypoints")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(waypoint))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(waypoint))
	}).Respond(c)
}
